### ISSUE TITLE
Combine with DevCards for interactive tutorials

### ISSUE THREAD

**Issue by kristianmandrup** [yogthos/cljs-eval-example#1]
I'm trying to set up an environment for teaching ClojureScript using DevCards.

Have been wanting to include a simple Code Editor (fx via CodeMirror)
and allow students to experiment directly in the browser in this fashion in combination
with Figwheel hot loading of code from the editor.

I'd basically like to turn some of the following: 

http://funcool.github.io/clojurescript-unraveled/
https://github.com/magomimmo/modern-cljs

Into a more interactive teaching tutorial for getting up and running with ClojureScript.
What do you think?

Perhaps even in combination with React/Om or Reagent?

https://github.com/pbostrom/om-codemirror

**Comment by yogthos** [comment]
I think that would be a great idea. I was thinking of making something like the [react-live-editor](https://github.com/joelburget/react-live-editor) with Reagent. I think the DevCards approach would be perfect for that.

**Comment by kristianmandrup** [comment]
Awesome! I'm only just getting my hands dirty with React and Clojure myself, but find DevCards invaluable for testing out ideas and getting immediate feedback :)
The future of Clojure books/tutorials IMO. 

BTW: Why Reagent instead of React/Om? Just curious...

**Comment by yogthos** [comment]
I find Reagent to be much more straight forward than Om, and both use React internally by the way. Reagent has a tiny API and it's very easy to get productive with. Om has a much steeper learning curve in my opinion.

**Comment by kristianmandrup** [comment]
Yes, been trying to wrap my head around Om.next the past few days... Perhaps I should start with a simpler Reagent model ;) I you start a live reagent editor project let me know...
